# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QHeaderView,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget)

from ui.widgets import FilesTree

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        self.action1 = QAction(MainWindow)
        self.action1.setObjectName(u"action1")
        self.actionAdd_new_folder = QAction(MainWindow)
        self.actionAdd_new_folder.setObjectName(u"actionAdd_new_folder")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionSelect_folder = QAction(MainWindow)
        self.actionSelect_folder.setObjectName(u"actionSelect_folder")
        self.actionClose_folder = QAction(MainWindow)
        self.actionClose_folder.setObjectName(u"actionClose_folder")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionCheck_for_updates = QAction(MainWindow)
        self.actionCheck_for_updates.setObjectName(u"actionCheck_for_updates")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.left_frame = QFrame(self.centralwidget)
        self.left_frame.setObjectName(u"left_frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_frame.sizePolicy().hasHeightForWidth())
        self.left_frame.setSizePolicy(sizePolicy)
        self.left_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.left_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.left_frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.path_lineEdit = QLineEdit(self.left_frame)
        self.path_lineEdit.setObjectName(u"path_lineEdit")
        self.path_lineEdit.setReadOnly(True)

        self.verticalLayout.addWidget(self.path_lineEdit)

        self.btn_frame = QFrame(self.left_frame)
        self.btn_frame.setObjectName(u"btn_frame")
        self.btn_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.btn_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.btn_frame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.back_pushButton = QPushButton(self.btn_frame)
        self.back_pushButton.setObjectName(u"back_pushButton")
        self.back_pushButton.setEnabled(False)

        self.horizontalLayout_2.addWidget(self.back_pushButton)

        self.forward_pushButton = QPushButton(self.btn_frame)
        self.forward_pushButton.setObjectName(u"forward_pushButton")
        self.forward_pushButton.setEnabled(False)

        self.horizontalLayout_2.addWidget(self.forward_pushButton)

        self.refresh_pushButton = QPushButton(self.btn_frame)
        self.refresh_pushButton.setObjectName(u"refresh_pushButton")
        self.refresh_pushButton.setEnabled(False)

        self.horizontalLayout_2.addWidget(self.refresh_pushButton)


        self.verticalLayout.addWidget(self.btn_frame)

        self.files_treeWidget = FilesTree(self.left_frame)
        self.files_treeWidget.setObjectName(u"files_treeWidget")
        self.files_treeWidget.setAcceptDrops(True)
        self.files_treeWidget.setLineWidth(1)

        self.verticalLayout.addWidget(self.files_treeWidget)


        self.horizontalLayout.addWidget(self.left_frame)

        self.right_tabWidget = QTabWidget(self.centralwidget)
        self.right_tabWidget.setObjectName(u"right_tabWidget")
        sizePolicy.setHeightForWidth(self.right_tabWidget.sizePolicy().hasHeightForWidth())
        self.right_tabWidget.setSizePolicy(sizePolicy)
        self.local_library_tab = QWidget()
        self.local_library_tab.setObjectName(u"local_library_tab")
        self.verticalLayout_2 = QVBoxLayout(self.local_library_tab)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.library_treeWidget = QTreeWidget(self.local_library_tab)
        self.library_treeWidget.setObjectName(u"library_treeWidget")
        self.library_treeWidget.setDragEnabled(True)
        self.library_treeWidget.setSortingEnabled(True)
        self.library_treeWidget.setHeaderHidden(False)
        self.library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_2.addWidget(self.library_treeWidget)

        self.addSeries_pushButton = QPushButton(self.local_library_tab)
        self.addSeries_pushButton.setObjectName(u"addSeries_pushButton")

        self.verticalLayout_2.addWidget(self.addSeries_pushButton)

        self.right_tabWidget.addTab(self.local_library_tab, "")
        self.anilist_library_tab = QWidget()
        self.anilist_library_tab.setObjectName(u"anilist_library_tab")
        self.verticalLayout_3 = QVBoxLayout(self.anilist_library_tab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.anilist_library_tabWidget = QTabWidget(self.anilist_library_tab)
        self.anilist_library_tabWidget.setObjectName(u"anilist_library_tabWidget")
        self.anilist_current_tab = QWidget()
        self.anilist_current_tab.setObjectName(u"anilist_current_tab")
        self.verticalLayout_4 = QVBoxLayout(self.anilist_current_tab)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.anilist_current_library_treeWidget = QTreeWidget(self.anilist_current_tab)
        self.anilist_current_library_treeWidget.setObjectName(u"anilist_current_library_treeWidget")
        self.anilist_current_library_treeWidget.setDragEnabled(True)
        self.anilist_current_library_treeWidget.setSortingEnabled(True)
        self.anilist_current_library_treeWidget.setHeaderHidden(False)
        self.anilist_current_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_4.addWidget(self.anilist_current_library_treeWidget)

        self.anilist_library_tabWidget.addTab(self.anilist_current_tab, "")
        self.anilist_repeating_tab = QWidget()
        self.anilist_repeating_tab.setObjectName(u"anilist_repeating_tab")
        self.verticalLayout_6 = QVBoxLayout(self.anilist_repeating_tab)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.anilist_repeating_library_treeWidget = QTreeWidget(self.anilist_repeating_tab)
        self.anilist_repeating_library_treeWidget.setObjectName(u"anilist_repeating_library_treeWidget")
        self.anilist_repeating_library_treeWidget.setDragEnabled(True)
        self.anilist_repeating_library_treeWidget.setSortingEnabled(True)
        self.anilist_repeating_library_treeWidget.setHeaderHidden(False)
        self.anilist_repeating_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_6.addWidget(self.anilist_repeating_library_treeWidget)

        self.anilist_library_tabWidget.addTab(self.anilist_repeating_tab, "")
        self.anilist_completed_tab = QWidget()
        self.anilist_completed_tab.setObjectName(u"anilist_completed_tab")
        self.verticalLayout_7 = QVBoxLayout(self.anilist_completed_tab)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.anilist_completed_library_treeWidget = QTreeWidget(self.anilist_completed_tab)
        self.anilist_completed_library_treeWidget.setObjectName(u"anilist_completed_library_treeWidget")
        self.anilist_completed_library_treeWidget.setDragEnabled(True)
        self.anilist_completed_library_treeWidget.setSortingEnabled(True)
        self.anilist_completed_library_treeWidget.setHeaderHidden(False)
        self.anilist_completed_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_7.addWidget(self.anilist_completed_library_treeWidget)

        self.anilist_library_tabWidget.addTab(self.anilist_completed_tab, "")
        self.anilist_paused_tab = QWidget()
        self.anilist_paused_tab.setObjectName(u"anilist_paused_tab")
        self.verticalLayout_8 = QVBoxLayout(self.anilist_paused_tab)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.anilist_paused_library_treeWidget = QTreeWidget(self.anilist_paused_tab)
        self.anilist_paused_library_treeWidget.setObjectName(u"anilist_paused_library_treeWidget")
        self.anilist_paused_library_treeWidget.setDragEnabled(True)
        self.anilist_paused_library_treeWidget.setSortingEnabled(True)
        self.anilist_paused_library_treeWidget.setHeaderHidden(False)
        self.anilist_paused_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_8.addWidget(self.anilist_paused_library_treeWidget)

        self.anilist_library_tabWidget.addTab(self.anilist_paused_tab, "")
        self.anilist_planning_tab = QWidget()
        self.anilist_planning_tab.setObjectName(u"anilist_planning_tab")
        self.verticalLayout_9 = QVBoxLayout(self.anilist_planning_tab)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.anilist_planning_library_treeWidget = QTreeWidget(self.anilist_planning_tab)
        self.anilist_planning_library_treeWidget.setObjectName(u"anilist_planning_library_treeWidget")
        self.anilist_planning_library_treeWidget.setDragEnabled(True)
        self.anilist_planning_library_treeWidget.setSortingEnabled(True)
        self.anilist_planning_library_treeWidget.setHeaderHidden(False)
        self.anilist_planning_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_9.addWidget(self.anilist_planning_library_treeWidget)

        self.anilist_library_tabWidget.addTab(self.anilist_planning_tab, "")
        self.anilist_dropped_tab = QWidget()
        self.anilist_dropped_tab.setObjectName(u"anilist_dropped_tab")
        self.verticalLayout_10 = QVBoxLayout(self.anilist_dropped_tab)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.anilist_dropped_library_treeWidget = QTreeWidget(self.anilist_dropped_tab)
        self.anilist_dropped_library_treeWidget.setObjectName(u"anilist_dropped_library_treeWidget")
        self.anilist_dropped_library_treeWidget.setDragEnabled(True)
        self.anilist_dropped_library_treeWidget.setSortingEnabled(True)
        self.anilist_dropped_library_treeWidget.setHeaderHidden(False)
        self.anilist_dropped_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_10.addWidget(self.anilist_dropped_library_treeWidget)

        self.anilist_library_tabWidget.addTab(self.anilist_dropped_tab, "")

        self.verticalLayout_3.addWidget(self.anilist_library_tabWidget)

        self.anilist_library_refresh_pushButton = QPushButton(self.anilist_library_tab)
        self.anilist_library_refresh_pushButton.setObjectName(u"anilist_library_refresh_pushButton")

        self.verticalLayout_3.addWidget(self.anilist_library_refresh_pushButton)

        self.right_tabWidget.addTab(self.anilist_library_tab, "")
        self.shikimori_tab = QWidget()
        self.shikimori_tab.setObjectName(u"shikimori_tab")
        self.verticalLayout_16 = QVBoxLayout(self.shikimori_tab)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.shikimori_library_tabWidget = QTabWidget(self.shikimori_tab)
        self.shikimori_library_tabWidget.setObjectName(u"shikimori_library_tabWidget")
        self.shikimori_watching_tab = QWidget()
        self.shikimori_watching_tab.setObjectName(u"shikimori_watching_tab")
        self.verticalLayout_5 = QVBoxLayout(self.shikimori_watching_tab)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.shikimori_watching_library_treeWidget = QTreeWidget(self.shikimori_watching_tab)
        self.shikimori_watching_library_treeWidget.setObjectName(u"shikimori_watching_library_treeWidget")
        self.shikimori_watching_library_treeWidget.setDragEnabled(True)
        self.shikimori_watching_library_treeWidget.setSortingEnabled(True)
        self.shikimori_watching_library_treeWidget.setHeaderHidden(False)
        self.shikimori_watching_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_5.addWidget(self.shikimori_watching_library_treeWidget)

        self.shikimori_library_tabWidget.addTab(self.shikimori_watching_tab, "")
        self.shikimori_rewatching_tab = QWidget()
        self.shikimori_rewatching_tab.setObjectName(u"shikimori_rewatching_tab")
        self.verticalLayout_11 = QVBoxLayout(self.shikimori_rewatching_tab)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.shikimori_rewatching_library_treeWidget = QTreeWidget(self.shikimori_rewatching_tab)
        self.shikimori_rewatching_library_treeWidget.setObjectName(u"shikimori_rewatching_library_treeWidget")
        self.shikimori_rewatching_library_treeWidget.setDragEnabled(True)
        self.shikimori_rewatching_library_treeWidget.setSortingEnabled(True)
        self.shikimori_rewatching_library_treeWidget.setHeaderHidden(False)
        self.shikimori_rewatching_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_11.addWidget(self.shikimori_rewatching_library_treeWidget)

        self.shikimori_library_tabWidget.addTab(self.shikimori_rewatching_tab, "")
        self.shikimori_completed_tab = QWidget()
        self.shikimori_completed_tab.setObjectName(u"shikimori_completed_tab")
        self.verticalLayout_12 = QVBoxLayout(self.shikimori_completed_tab)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.shikimori_completed_library_treeWidget = QTreeWidget(self.shikimori_completed_tab)
        self.shikimori_completed_library_treeWidget.setObjectName(u"shikimori_completed_library_treeWidget")
        self.shikimori_completed_library_treeWidget.setDragEnabled(True)
        self.shikimori_completed_library_treeWidget.setSortingEnabled(True)
        self.shikimori_completed_library_treeWidget.setHeaderHidden(False)
        self.shikimori_completed_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_12.addWidget(self.shikimori_completed_library_treeWidget)

        self.shikimori_library_tabWidget.addTab(self.shikimori_completed_tab, "")
        self.shikimori_on_hold_tab = QWidget()
        self.shikimori_on_hold_tab.setObjectName(u"shikimori_on_hold_tab")
        self.verticalLayout_13 = QVBoxLayout(self.shikimori_on_hold_tab)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.shikimori_on_hold_library_treeWidget = QTreeWidget(self.shikimori_on_hold_tab)
        self.shikimori_on_hold_library_treeWidget.setObjectName(u"shikimori_on_hold_library_treeWidget")
        self.shikimori_on_hold_library_treeWidget.setDragEnabled(True)
        self.shikimori_on_hold_library_treeWidget.setSortingEnabled(True)
        self.shikimori_on_hold_library_treeWidget.setHeaderHidden(False)
        self.shikimori_on_hold_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_13.addWidget(self.shikimori_on_hold_library_treeWidget)

        self.shikimori_library_tabWidget.addTab(self.shikimori_on_hold_tab, "")
        self.shikimori_planned_tab = QWidget()
        self.shikimori_planned_tab.setObjectName(u"shikimori_planned_tab")
        self.verticalLayout_14 = QVBoxLayout(self.shikimori_planned_tab)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.shikimori_planned_library_treeWidget = QTreeWidget(self.shikimori_planned_tab)
        self.shikimori_planned_library_treeWidget.setObjectName(u"shikimori_planned_library_treeWidget")
        self.shikimori_planned_library_treeWidget.setDragEnabled(True)
        self.shikimori_planned_library_treeWidget.setSortingEnabled(True)
        self.shikimori_planned_library_treeWidget.setHeaderHidden(False)
        self.shikimori_planned_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_14.addWidget(self.shikimori_planned_library_treeWidget)

        self.shikimori_library_tabWidget.addTab(self.shikimori_planned_tab, "")
        self.shikimori_dropped_tab = QWidget()
        self.shikimori_dropped_tab.setObjectName(u"shikimori_dropped_tab")
        self.verticalLayout_15 = QVBoxLayout(self.shikimori_dropped_tab)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.shikimori_dropped_library_treeWidget = QTreeWidget(self.shikimori_dropped_tab)
        self.shikimori_dropped_library_treeWidget.setObjectName(u"shikimori_dropped_library_treeWidget")
        self.shikimori_dropped_library_treeWidget.setDragEnabled(True)
        self.shikimori_dropped_library_treeWidget.setSortingEnabled(True)
        self.shikimori_dropped_library_treeWidget.setHeaderHidden(False)
        self.shikimori_dropped_library_treeWidget.header().setStretchLastSection(False)

        self.verticalLayout_15.addWidget(self.shikimori_dropped_library_treeWidget)

        self.shikimori_library_tabWidget.addTab(self.shikimori_dropped_tab, "")

        self.verticalLayout_16.addWidget(self.shikimori_library_tabWidget)

        self.shikimori_library_refresh_pushButton = QPushButton(self.shikimori_tab)
        self.shikimori_library_refresh_pushButton.setObjectName(u"shikimori_library_refresh_pushButton")

        self.verticalLayout_16.addWidget(self.shikimori_library_refresh_pushButton)

        self.right_tabWidget.addTab(self.shikimori_tab, "")

        self.horizontalLayout.addWidget(self.right_tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 33))
        self.menuLibrary = QMenu(self.menubar)
        self.menuLibrary.setObjectName(u"menuLibrary")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuLibrary.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuLibrary.addSeparator()
        self.menuLibrary.addAction(self.actionSelect_folder)
        self.menuLibrary.addAction(self.actionClose_folder)
        self.menuLibrary.addAction(self.actionExit)
        self.menuTools.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCheck_for_updates)

        self.retranslateUi(MainWindow)

        self.right_tabWidget.setCurrentIndex(0)
        self.anilist_library_tabWidget.setCurrentIndex(0)
        self.shikimori_library_tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"NekoDesk", None))
        self.action1.setText(QCoreApplication.translate("MainWindow", u"1.", None))
        self.actionAdd_new_folder.setText(QCoreApplication.translate("MainWindow", u"Add new folder...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.actionSelect_folder.setText(QCoreApplication.translate("MainWindow", u"Select folder", None))
#if QT_CONFIG(shortcut)
        self.actionSelect_folder.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionClose_folder.setText(QCoreApplication.translate("MainWindow", u"Close folder", None))
#if QT_CONFIG(shortcut)
        self.actionClose_folder.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionCheck_for_updates.setText(QCoreApplication.translate("MainWindow", u"Check for updates", None))
        self.path_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Path", None))
        self.back_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u2b60", None))
        self.forward_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u2b62", None))
        self.refresh_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u27f3", None))
        ___qtreewidgetitem = self.files_treeWidget.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"Folder", None))
        ___qtreewidgetitem1 = self.library_treeWidget.headerItem()
        ___qtreewidgetitem1.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem1.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.addSeries_pushButton.setText(QCoreApplication.translate("MainWindow", u"Add series", None))
        self.right_tabWidget.setTabText(self.right_tabWidget.indexOf(self.local_library_tab), QCoreApplication.translate("MainWindow", u"Local", None))
        ___qtreewidgetitem2 = self.anilist_current_library_treeWidget.headerItem()
        ___qtreewidgetitem2.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem2.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem2.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.anilist_library_tabWidget.setTabText(self.anilist_library_tabWidget.indexOf(self.anilist_current_tab), QCoreApplication.translate("MainWindow", u"Watching", None))
        ___qtreewidgetitem3 = self.anilist_repeating_library_treeWidget.headerItem()
        ___qtreewidgetitem3.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem3.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem3.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.anilist_library_tabWidget.setTabText(self.anilist_library_tabWidget.indexOf(self.anilist_repeating_tab), QCoreApplication.translate("MainWindow", u"Rewatching", None))
        ___qtreewidgetitem4 = self.anilist_completed_library_treeWidget.headerItem()
        ___qtreewidgetitem4.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem4.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem4.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.anilist_library_tabWidget.setTabText(self.anilist_library_tabWidget.indexOf(self.anilist_completed_tab), QCoreApplication.translate("MainWindow", u"Completed", None))
        ___qtreewidgetitem5 = self.anilist_paused_library_treeWidget.headerItem()
        ___qtreewidgetitem5.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem5.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem5.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem5.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.anilist_library_tabWidget.setTabText(self.anilist_library_tabWidget.indexOf(self.anilist_paused_tab), QCoreApplication.translate("MainWindow", u"Paused", None))
        ___qtreewidgetitem6 = self.anilist_planning_library_treeWidget.headerItem()
        ___qtreewidgetitem6.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem6.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem6.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem6.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.anilist_library_tabWidget.setTabText(self.anilist_library_tabWidget.indexOf(self.anilist_planning_tab), QCoreApplication.translate("MainWindow", u"Planning", None))
        ___qtreewidgetitem7 = self.anilist_dropped_library_treeWidget.headerItem()
        ___qtreewidgetitem7.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem7.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem7.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem7.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.anilist_library_tabWidget.setTabText(self.anilist_library_tabWidget.indexOf(self.anilist_dropped_tab), QCoreApplication.translate("MainWindow", u"Dropped", None))
        self.anilist_library_refresh_pushButton.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.right_tabWidget.setTabText(self.right_tabWidget.indexOf(self.anilist_library_tab), QCoreApplication.translate("MainWindow", u"AniList", None))
        ___qtreewidgetitem8 = self.shikimori_watching_library_treeWidget.headerItem()
        ___qtreewidgetitem8.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem8.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem8.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem8.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.shikimori_library_tabWidget.setTabText(self.shikimori_library_tabWidget.indexOf(self.shikimori_watching_tab), QCoreApplication.translate("MainWindow", u"Watching", None))
        ___qtreewidgetitem9 = self.shikimori_rewatching_library_treeWidget.headerItem()
        ___qtreewidgetitem9.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem9.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem9.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem9.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.shikimori_library_tabWidget.setTabText(self.shikimori_library_tabWidget.indexOf(self.shikimori_rewatching_tab), QCoreApplication.translate("MainWindow", u"Rewatching", None))
        ___qtreewidgetitem10 = self.shikimori_completed_library_treeWidget.headerItem()
        ___qtreewidgetitem10.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem10.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem10.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem10.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.shikimori_library_tabWidget.setTabText(self.shikimori_library_tabWidget.indexOf(self.shikimori_completed_tab), QCoreApplication.translate("MainWindow", u"Completed", None))
        ___qtreewidgetitem11 = self.shikimori_on_hold_library_treeWidget.headerItem()
        ___qtreewidgetitem11.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem11.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem11.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem11.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.shikimori_library_tabWidget.setTabText(self.shikimori_library_tabWidget.indexOf(self.shikimori_on_hold_tab), QCoreApplication.translate("MainWindow", u"On Hold", None))
        ___qtreewidgetitem12 = self.shikimori_planned_library_treeWidget.headerItem()
        ___qtreewidgetitem12.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem12.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem12.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem12.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.shikimori_library_tabWidget.setTabText(self.shikimori_library_tabWidget.indexOf(self.shikimori_planned_tab), QCoreApplication.translate("MainWindow", u"Planned to Watch", None))
        ___qtreewidgetitem13 = self.shikimori_dropped_library_treeWidget.headerItem()
        ___qtreewidgetitem13.setText(3, QCoreApplication.translate("MainWindow", u"Episodes", None))
        ___qtreewidgetitem13.setText(2, QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtreewidgetitem13.setText(1, QCoreApplication.translate("MainWindow", u"Year", None))
        ___qtreewidgetitem13.setText(0, QCoreApplication.translate("MainWindow", u"Title", None))
        self.shikimori_library_tabWidget.setTabText(self.shikimori_library_tabWidget.indexOf(self.shikimori_dropped_tab), QCoreApplication.translate("MainWindow", u"Dropped", None))
        self.shikimori_library_refresh_pushButton.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.right_tabWidget.setTabText(self.right_tabWidget.indexOf(self.shikimori_tab), QCoreApplication.translate("MainWindow", u"Shikimori", None))
        self.menuLibrary.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

